package com.Colegio.colegio;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.transaction.Transactional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private AlumnoRespository AlumnoRespository;
	@Autowired
	private CicloRepository CicloRepository;

	@RequestMapping(path="/addAlumnos") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String name,@RequestParam String apellido,@RequestParam int ciclo) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Alumnos a = new Alumnos();

		a.setNombre(name);
		a.setApellido(apellido);
		a.setId_ciclo(ciclo);
		AlumnoRespository.save(a);

		return "saved";

	}

	@RequestMapping(path="/addCiclos") // Map ONLY POST Requests
	public @ResponseBody String addNewCiclo (@RequestParam String name,@RequestParam String especialidad) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Ciclos c = new Ciclos();

		c.setName(name);
		c.setEspecialidad(especialidad);
		CicloRepository.save(c);

		return "saved";

	}

	@Transactional
	@RequestMapping(path="/deleteAlumno") // Map ONLY POST Requests
	public @ResponseBody String deleteAlumno (@RequestParam String nombre) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		AlumnoRespository.deleteByNombre(nombre);
		return "delete";

	}

	@RequestMapping(path="/deleteCiclo") // Map ONLY POST Requests
	public @ResponseBody String deleteCiclo (@RequestParam String nombre) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		CicloRepository.deleteByNombre(nombre);
		return "delete";

	}


	@GetMapping(path="/allAlumnos")
	public @ResponseBody Iterable<Alumnos> getAllUsers() {
		// This returns a JSON or XML with the users
		return AlumnoRespository.findAll();
	}

	@GetMapping(path="/allCiclos")
	public @ResponseBody Iterable<Ciclos> TodosCiclos() {
		// This returns a JSON or XML with the users
		return CicloRepository.findAll();
	}

	@GetMapping(path="/byName")
	public @ResponseBody Alumnos busquedaNombre(String name){

		return AlumnoRespository.findByNombre(name);

	}

	@GetMapping(path="/byCiclo")
	public @ResponseBody Ciclos busquedaCiclo(String ciclo){

		return CicloRepository.findByEspecialidad(ciclo);

	}
}